### ISSUE TITLE
database tables

### ISSUE THREAD

**Issue by thanat** [dereuromark/cakefest#13]
Hi, i'm new to the CakePHP 3, all is bit confusing and seems much more complicated than CakePHP 2.x
I want to start using CakePHP 3 and i choose this repo as "learning" point.
i've installed the master branch on my local machine, all is set up.

But i'm getting error.
Error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'cake_cakefest.users' doesn't exist

where can i find the initial database setup for testing ? how can i import tables ?

many thanks
Martin

**Comment by dereuromark** [comment]
I probably forgot to add the sql, here is it now: https://github.com/dereuromark/cakefest/commit/9113c366a437b058237bb1c84a20996682fab3ed

PS: You need to execute the Migrations shell
