### ISSUE TITLE
migrations error

### ISSUE THREAD

**Issue by thanat** [dereuromark/cakefest#14]
following the issue #13, i've tried to run the migrations 

```
bin/cake migrations migrate
```

following the migrations documentation on cakepph website, but getting error:

```
[InvalidArgumentException]                                                                        
There was a problem connecting to the database: SQLSTATE[HY000] [2002] No such file or directory
```

my app_local.php is correctly set with database details, i've even updated the database detail in app.php file but no luck.  

any advice ?

many thanks,
Martin

**Comment by dereuromark** [comment]
You can also manually run the SQL in phpmyadmin etc. No need to run it via migrations shell.
